# Generated by Django 3.0.3 on 2020-06-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0008_re'),
    ]

    operations = [
        migrations.CreateModel(
            name='Covid19_coun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=100)),
                ('Korea_South', models.FloatField(null=True)),
                ('Japan', models.FloatField(null=True)),
                ('Australia', models.FloatField(null=True)),
                ('China', models.FloatField(null=True)),
                ('Malaysia', models.FloatField(null=True)),
            ],
        ),
    ]
